### PR TITLE
Replaced Sokol with Chiado

### PR DESCRIPTION
**Pull request by kaushalrajbacancy**
- Replaced the configuration of Sokol with Chiado

## Description

- As we are not using Sokol. So, we have added Chiado instead

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### CODE REVIEW

**Comment by kaushalrajbacancy** [comment]
@marie-fourier @lbw33 @vignesha22 I have made the required changes and the env is also ready. I haven't deployed any contracts yet. 

I ran the npm run build. So, it has updated deployments.md, and I can see deployments/Sokol. 

It has generated new constants in the dist folder too. Please let me know if I need to make any changes there.

**Review by marie-fourier — APPROVED** [review]

**Comment by kaushalrajbacancy** [comment]
@ch4r10t33r @marie-fourier @lbw33 @vignesha22 I have deployed the contract and successfully worked in one go. This has updated a few more files. Please review this.

**Review by lbw33 — APPROVED** [review]

**Comment by marie-fourier** [comment]
I will add Chiado relayers to GatewayV2 and approve the pr

**Comment by kaushalrajbacancy** [comment]
> I will add Chiado relayers to GatewayV2 and approve the pr

@marie-fourier I will wait for the confirmation.

**Review by marie-fourier — APPROVED** [review]
oh sorry, we don't have any relayers there yet @kaushalrajbacancy 
approved

**Pull request merged**
